//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atributo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public atributo()
        {
            this.atributo_por_equipo = new HashSet<atributo_por_equipo>();
        }
    
        public int idatributo { get; set; }
        public string nombre { get; set; }
        public int tipo_dato_fk { get; set; }
        public sbyte es_requerido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<atributo_por_equipo> atributo_por_equipo { get; set; }
        public virtual tipo_dato tipo_dato { get; set; }
    }
}
