//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atributo_por_equipo
    {
        public int atributo_fk { get; set; }
        public int equipo_fk { get; set; }
        public string valor_atributo { get; set; }
    
        public virtual atributo atributo { get; set; }
        public virtual equipo equipo { get; set; }
    }
}
