//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class marca_modelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public marca_modelo()
        {
            this.equipo = new HashSet<equipo>();
        }
    
        public int idmarca_modelo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }

        public string marca_modelo_string
        {
            get
            {
                return this.marca + " - " + this.modelo;
            }
        
        }
       

        public string especificaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipo> equipo { get; set; }
    }
}
