//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using System.ComponentModel;

    using System.Web.Mvc;

    public partial class puerto_por_equipo
    {

        public int puerto_por_equipo_unique_id
        { get; set; }

        public int equipo_fk { get; set; }
        [UIHint("Puerto")]
        public int puerto_fk { get; set; }
        public string numero_de_puertos { get; set; }

        public string puerto_nombre { get; set; }

        public virtual equipo equipo { get; set; }
        public virtual puerto puerto { get; set; }
    }
}
