//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public software()
        {
            this.software_por_equipo = new HashSet<software_por_equipo>();
        }
    
        public int idsoftware { get; set; }
        public string nombre { get; set; }
        public string version { get; set; }
        public string codigo { get; set; }
        public Nullable<int> proveedor_fk { get; set; }
        public Nullable<int> tipo_software_fk { get; set; }
        public string informacion_tecnica { get; set; }
        public string configuraciones { get; set; }
        public sbyte es_activo { get; set; }
        public Nullable<int> licencias_adquiridas { get; set; }
        public Nullable<int> licencias_instaladas { get; set; }
    
        public virtual proveedor proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<software_por_equipo> software_por_equipo { get; set; }
        public virtual tipo_de_software tipo_de_software { get; set; }
    }
}
