//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    using System.ComponentModel;
   
    using System.Web.Mvc;


    public partial class software_por_equipo
    {

        public int software_por_equipo_unique_id
        { get; set; }

        public int equipo_fk { get; set; }
        [UIHint("Software")]
        public int software_fk { get; set; }
        public string observaciones { get; set; }

        public string software_nombre { get;set;}
    
        public virtual equipo equipo { get; set; }
        //[UIHint("Software")]
        public virtual software software { get; set; }
    }
}
